the unexpected pull request for you
zzirakadze/Otiastvis pull request #4
Opened 2022-05-23 14:47 UTC by zzirakadze

--

2022-05-23 14:58 UTC, asopromadze requested changes

2022-05-23 14:58 UTC, asopromadze commented on messageforu
> +  OTIA ra xdeba chemi dzma raa ambebia aq ?
You need to be clear about subject :smile:

2022-08-03 12:06 UTC, merged

2022-10-11 09:03 UTC, zzirakadze commented
Test are executing via pipeline from different repo

On Mon, 23 May 2022, 18:59 Anri Sopromadze, ***@***.***>
wrote:

> Please provide more details what you'v changed, we have test driven
> development so write test's too
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zzirakadze/Otiastvis/pull/4#issuecomment-1134786113>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOLOP7KU4ZZFLR22SAGGD4DVLOMNBANCNFSM5WWDOTKQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-11 12:41 UTC, asopromadze commented
რა ჯანდაბას ჩალიჩობ ? :smile:

2022-10-11 12:42 UTC, zzirakadze commented
ვერ მივხვდი ძმაო რაზე მეკითხები ?

On Tue, 11 Oct 2022, 16:41 Anri Sopromadze, ***@***.***>
wrote:

> რა ჯანდაბას ჩალიჩობ ? 😄
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zzirakadze/Otiastvis/pull/4#issuecomment-1274627655>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOLOP7PZ42NKPFS4MOROJRLWCVOAVANCNFSM5WWDOTKQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-10-12 07:55 UTC, asopromadze commented
![image](https://user-images.githubusercontent.com/61462002/195283946-28885ab2-590c-4d71-926a-cb58856c739f.png)

2022-10-12 08:11 UTC, zzirakadze commented
ხუიევიზნაეტ ვაბშე აე შევსულვარ გიტჰაბზე  გუშინ

On Wed, 12 Oct 2022, 11:56 Anri Sopromadze, ***@***.***>
wrote:

> [image: image]
> <https://user-images.githubusercontent.com/61462002/195283946-28885ab2-590c-4d71-926a-cb58856c739f.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zzirakadze/Otiastvis/pull/4#issuecomment-1275746267>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOLOP7MUP5PZRVFRK77RUO3WCZVJBANCNFSM5WWDOTKQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>